### ISSUE TITLE
请问markType能否自定义内容

### ISSUE THREAD

**Issue by swanchou** [TangSY/vue-hash-calendar#107]
请问markType能否自定义内容 我想在markType里面显示我需要的文字请问有什么办法解决吗

**Comment by TangSY** [comment]
![image](https://user-images.githubusercontent.com/16008985/182070949-99ec442f-9dbe-44b4-aa03-accd12bebd3a.png)
用 day slot 结合 isMarked 可以实现

**Comment by swanchou** [comment]
谢谢作者回复，他能传入动态文字吗，我想要的是如果被标记的同时传入相关标记文字类似截图
![QQ截图20220801140446](https://user-images.githubusercontent.com/60967072/182082643-b5561e7b-96b8-4658-a238-533a706f1bce.png)

**Comment by TangSY** [comment]
可以，你试一下就知道了

**Comment by swanchou** [comment]
求作者大大给个示例呗，我试了试isMarked只有true和false 这个无法判断的，因为要展示的类型比较多

**Comment by TangSY** [comment]
可以结合日期一起判断
