### ISSUE TITLE
请问能不能暴露出来个自定义的today跳转方法,我通过$refs报了错误  this.$refs.calendars.calculateCalendarOfThreeMonth方法undefined

### ISSUE THREAD

**Issue by zb1843** [TangSY/vue-hash-calendar#108]
goToday(timer="2022/08/31") {
			// this.refs.calendar.today('2022/0831')

			this.$set(this.$refs.calendars.checkedDate, 'day', new Date(timer).getDate());
			this.$refs.calendars.yearOfCurrentShow = new Date(timer).getFullYear(); // 当前日历展示的年份
			this.$refs.calendars.monthOfCurrentShow = new Date(timer).getMonth(); // 当前日历展示的月份
			
			console.log( this.$refs.calendars);
		this.$refs.calendars.calculateCalendarOfThreeMonth(this.$refs.calendars.yearOfCurrentShow,this.$refs.calendars.monthOfCurrentShow);
			if (this.$refs.calendars.isShowWeek) {
				setTimeout(() => {
					this.$refs.calendars.isTouching = true;
					// fix: 周视图无法通过点击今天按钮返回  https://github.com/TangSY/vue-hash-calendar/issues/87
					this.$set(this.$refs.calendars.checkedDate, 'year', new Date(timer).getFullYear());
					this.$set(this.$refs.calendars.checkedDate, 'month', new Date(timer).getMonth());
					this.$refs.calendars.showWeek();
				}, this.$refs.calendars.transitionDuration * 1000);
			}
		},

**Comment by TangSY** [comment]
this.refs.calendar.today()，这个方法可以返回今天呀，你要重新定义“今天”吗？还是说只是想跳转到指定的日期？

**Comment by zb1843** [comment]
我是想跳转到指定日期的

**Comment by TangSY** [comment]
你修改 defalutDatetime 试试

**Comment by zb1843** [comment]
我试过了   可以跳过去   但是不实用 跳第二次组件就变空白了

**Comment by zb1843** [comment]
![1663141846980](https://user-images.githubusercontent.com/100667892/190094383-773be517-c387-4aef-ab4b-d4df67755a2a.jpg)

**Comment by zb1843** [comment]
抱歉哈 有保密协议所以图片不得不打个码

**Comment by TangSY** [comment]
好，我看看

**Comment by TangSY** [comment]
我这边抽空测试了一下，修改defaultDatetime是可以正常跳转的，且没有报错信息。你可以给个复现链接？
![image](https://user-images.githubusercontent.com/16008985/191153191-51b72c0d-e355-41c5-a731-4708ccded32a.png)

`
 <button @click="changeDate('2022/09/23 19:04')">11111</button>
 <button @click="changeDate('2023/04/11 22:04')">22222</button>
 <button @click="changeDate('2025/08/09 22:04')">22222</button>
`
` 
changeDate(date) {
    this.defaultDatetime = new Date(date);
},
`

**Comment by zb1843** [comment]
好的,我今天晚会弄个demo 复现下

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年9月20日 10:22
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [TangSY/vue-hash-calendar] 请问能不能暴露出来个自定义的today跳转方法,我通过$refs报了错误 this.$refs.calendars.calculateCalendarOfThreeMonth方法undefined (Issue #108)


我这边抽空测试了一下，修改defaultDatetime是可以正常跳转的，且没有报错信息。你可以给个复现链接？
[image]<https://user-images.githubusercontent.com/16008985/191153191-51b72c0d-e355-41c5-a731-4708ccded32a.png>

<button @click="changeDate('2022/09/23 19:04')">11111</button> <button @click="changeDate('2023/04/11 22:04')">22222</button> <button @click="changeDate('2025/08/09 22:04')">22222</button>
changeDate(date) { this.defaultDatetime = new Date(date); },

―

**Comment by zb1843** [comment]
已解决

**Comment by zb1843** [comment]
你好作者,我测试了一下demo现在没问题了;之前图片NAN的问题是我模拟用户频繁调用today方法出现的现状。非常感谢您抽时间帮我解惑,谢谢项目已点赞

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年9月20日 10:22
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [TangSY/vue-hash-calendar] 请问能不能暴露出来个自定义的today跳转方法,我通过$refs报了错误 this.$refs.calendars.calculateCalendarOfThreeMonth方法undefined (Issue #108)


我这边抽空测试了一下，修改defaultDatetime是可以正常跳转的，且没有报错信息。你可以给个复现链接？
[image]<https://user-images.githubusercontent.com/16008985/191153191-51b72c0d-e355-41c5-a731-4708ccded32a.png>

<button @click="changeDate('2022/09/23 19:04')">11111</button> <button @click="changeDate('2023/04/11 22:04')">22222</button> <button @click="changeDate('2025/08/09 22:04')">22222</button>
changeDate(date) { this.defaultDatetime = new Date(date); },

―
