### ISSUE TITLE
请问用CDN怎么引入？

### ISSUE THREAD

**Issue by yzs1228** [TangSY/vue-hash-calendar#11]

**Comment by TangSY** [comment]
在 index.html 加入这两行：
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/vue-hash-calendar@1.1.17/lib/vue-hash-calendar.umd.min.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vue-hash-calendar@1.1.17/lib/vue-hash-calendar.css">

在 webpack 配置中，加入以下配置。
externals: {
    'vue-hash-calendar': 'VueHashCalendar'
},

**Comment by TangSY** [comment]
在 index.html 加入以下两个 CDN 链接：
js CDN：https://cdn.jsdelivr.net/npm/vue-hash-calendar@1.1.17/lib/vue-hash-calendar.umd.min.js
css CDN:  https://cdn.jsdelivr.net/npm/vue-hash-calendar@1.1.17/lib/vue-hash-calendar.css

然后在 webpack 配置中，加入以下配置。
externals: {
'vue-hash-calendar': 'VueHashCalendar'
},
