### ISSUE TITLE
周试图时，不同月份的日期点击试图会滚动，可否不滚动

### ISSUE THREAD

**Issue by rourou1107** [TangSY/vue-hash-calendar#110]
周试图时，不同月份的日期点击切换时试图会滚动，可否不滚动

**Comment by rourou1107** [comment]
https://user-images.githubusercontent.com/37865697/192084650-8148b383-2194-4c77-ab50-454d835bee90.mp4

**Comment by TangSY** [comment]
好，我处理一下

**Comment by rourou1107** [comment]
> 好，我处理一下

嗯嗯，谢谢啦

**Comment by TangSY** [comment]
已修复，升级版本至 1.4.26 。
使用 isAutoChangeMonth 属性控制是否切换月份
