### ISSUE TITLE
不同月份的日期点击切换，页面抖动

### ISSUE THREAD

**Issue by rourou1107** [TangSY/vue-hash-calendar#111]
https://user-images.githubusercontent.com/37865697/192923839-90e39619-9e22-4961-b803-db60a497c3ae.mp4

**Comment by TangSY** [comment]
跟 #110 这个是同一个问题

**Comment by rourou1107** [comment]
> 跟 #110 这个是同一个问题

是的，刚没看到上次我提问的那个问题，我以为那个问题没了，就又提了一个
