### ISSUE TITLE
设置isAutoChangeMonth为false后，滑动试图，日期选中的位置没有跟随上一次选中的位置动。可否跟随上一次选中的位置动

### ISSUE THREAD

**Issue by rourou1107** [TangSY/vue-hash-calendar#112]
https://user-images.githubusercontent.com/37865697/193210311-d4a8a8a7-0c7f-4d83-a617-f110739b1486.mp4

https://user-images.githubusercontent.com/37865697/193210340-356143a7-2b3d-447d-a703-058c7cc7fb9e.mp4

**Comment by TangSY** [comment]
好，我看看

**Comment by TangSY** [comment]
已修复
