### ISSUE TITLE
这个需要单独安装农历插件吗，导入失败了

### ISSUE THREAD

**Issue by HuangHua1** [TangSY/vue-hash-calendar#115]
![image](https://user-images.githubusercontent.com/6121553/198562906-4803818d-3996-400b-bc47-1650b5b21006.png)
![image](https://user-images.githubusercontent.com/6121553/198563027-653df6a2-ccf3-4e80-9fea-3f4c224f96ec.png)
![image](https://user-images.githubusercontent.com/6121553/198563168-85643259-673b-4e09-a98c-a2c431f73fbf.png)

**Comment by TangSY** [comment]
把同级目录下的这个 lunar 文件也一并复制过去就好了
