### ISSUE TITLE
可以选择时间范围吗？类似酒店入住时间范围选择

### ISSUE THREAD

**Issue by tuotuogenjudi** [TangSY/vue-hash-calendar#12]

**Comment by TangSY** [comment]
暂时不行，后期考虑加入该功能。
目前可以使用调用两次本插件替代



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "tuotuogenjudi"<notifications@github.com&gt;; 
发送时间: 2020年3月4日(星期三) 凌晨1:26
收件人: "TangSY/vue-hash-calendar"<vue-hash-calendar@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [TangSY/vue-hash-calendar] 可以选择时间范围吗？类似酒店入住时间范围选择 (#12)

**Comment by wzl26999821** [comment]
slot这个具体是怎么使用呢？

**Comment by JunkeWen** [comment]
您好，请问一下控件引入进来之后  怎么没有确认按钮？ 只有 “今天” 字样

**Comment by TangSY** [comment]
dialog形式的默认有确认按钮，inline的没有，也可以通过action&nbsp;slot自己添加




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JunkeWen"<notifications@github.com&gt;; 
发送时间: 2020年7月9日(星期四) 上午10:41
收件人: "TangSY/vue-hash-calendar"<vue-hash-calendar@noreply.github.com&gt;; 
抄送: "【T】"<337828932@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [TangSY/vue-hash-calendar] 可以选择时间范围吗？类似酒店入住时间范围选择 (#12)





 
您好，请问一下控件引入进来之后  怎么没有确认按钮？ 只有 “今天” 字样

**Comment by JunkeWen** [comment]
好的  感谢

**Comment by TangSY** [comment]
https://hxkj.vip/calendar

已支持
