### ISSUE TITLE
希望考虑做双语版本？

### ISSUE THREAD

**Issue by Zalefs** [TangSY/vue-hash-calendar#13]
能不能指定我们设置对应参数，进行该组件的中英文版本切换？

**Comment by TangSY** [comment]
可以考虑




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zalefs"<notifications@github.com&gt;; 
发送时间: 2020年3月17日(星期二) 下午3:05
收件人: "TangSY/vue-hash-calendar"<vue-hash-calendar@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [TangSY/vue-hash-calendar] 能不能考虑做双语版本？ (#13)





 
能不能指定我们设置对应参数，进行该组件的中英文版本切换？

**Comment by TangSY** [comment]
已添加 lang 属性，具体用法查看文档，更新组件至 1.2.2 版本即可使用。
