### ISSUE TITLE
可以默认显示周视图吗

### ISSUE THREAD

**Issue by jiangshao2014** [TangSY/vue-hash-calendar#14]
你好，请问可以弄成默认显示周视图或者月视图吗？现在默认显示月视图

**Comment by TangSY** [comment]
isShowWeekView&nbsp; &nbsp;属性设置为&nbsp;true




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jiangshao2014"<notifications@github.com&gt;; 
发送时间: 2020年3月19日(星期四) 下午5:55
收件人: "TangSY/vue-hash-calendar"<vue-hash-calendar@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [TangSY/vue-hash-calendar] 可以默认显示周视图吗 (#14)





 
你好，请问可以弄成默认显示周视图或者月视图吗？现在默认显示月视图

**Comment by TangSY** [comment]
isShowWeekView：属性设置为true

**Comment by jiangshao2014** [comment]
已经设置了，默认还是月视图，需要滑动后才变更为周视图，代码如下
<vue-hash-calendar
			ref="picker"
			model="inline"
			:scroll-change-date="true"
			:visible.sync="isShowCalendar"
			:default-datetime="defaultDatetime"
			:is-show-week-view="true"
			:minute-step="1"
			:mark-date="markDate"
			mark-type="dot"
			format="YY-MM-DD"
			week-start="sunday"
			picker-type="date"
			:show-today-button="true"
			:disabled-week-view="false"
			@click="dateClick"
		></vue-hash-calendar>

**Comment by TangSY** [comment]
好，我看下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "kang"<notifications@github.com&gt;; 
发送时间: 2020年3月19日(星期四) 晚上6:03
收件人: "TangSY/vue-hash-calendar"<vue-hash-calendar@noreply.github.com&gt;; 
抄送: "【T】"<337828932@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [TangSY/vue-hash-calendar] 可以默认显示周视图吗 (#14)





 
已经设置了，默认还是月视图，需要滑动后才变更为周视图，代码如下
 <vue-hash-calendar
 ref="picker"
 model="inline"
 :scroll-change-date="true"
 :visible.sync="isShowCalendar"
 :default-datetime="defaultDatetime"
 :is-show-week-view="true"
 :minute-step="1"
 :mark-date="markDate"
 mark-type="dot"
 format="YY-MM-DD"
 week-start="sunday"
 picker-type="date"
 :show-today-button="true"
 :disabled-week-view="false"
 @click="dateClick"
 &gt;

**Comment by TangSY** [comment]
已修复，更新日历组件至最新版本 1.1.25
