### ISSUE TITLE
选择时间有点bug

### ISSUE THREAD

**Issue by chenjiecloud** [TangSY/vue-hash-calendar#15]
![image](https://user-images.githubusercontent.com/31178795/77241301-061a4580-6c2b-11ea-946c-c7a80ac226aa.png)

**Comment by TangSY** [comment]
什么手机型号



---原始邮件---
发件人: "Asaki"<notifications@github.com&gt;
发送时间: 2020年3月22日(周日) 上午10:51
收件人: "TangSY/vue-hash-calendar"<vue-hash-calendar@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [TangSY/vue-hash-calendar] 选择时间有点bug (#15)

**Comment by chenjiecloud** [comment]
chrome 移动端

**Comment by chenjiecloud** [comment]
使用2个组件选择时间段

**Comment by TangSY** [comment]
收到



---原始邮件---
发件人: "Asaki"<notifications@github.com&gt;
发送时间: 2020年3月22日(周日) 中午11:23
收件人: "TangSY/vue-hash-calendar"<vue-hash-calendar@noreply.github.com&gt;;
抄送: "TangSY"<337828932@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [TangSY/vue-hash-calendar] 选择时间有点bug (#15)




 
使用2个组件选择时间段

**Comment by chenjiecloud** [comment]
有什么解决的办法吗？

**Comment by TangSY** [comment]
该BUG已修复，这两天也在搞双语版本，今晚会一起发布版本




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Asaki"<notifications@github.com&gt;; 
发送时间: 2020年3月24日(星期二) 上午10:06
收件人: "TangSY/vue-hash-calendar"<vue-hash-calendar@noreply.github.com&gt;; 
抄送: "【T】"<337828932@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [TangSY/vue-hash-calendar] 选择时间有点bug (#15)





 
有什么解决的办法吗？

**Comment by TangSY** [comment]
已修复，更新组件至 1.2.2 版本即可使用

**Comment by chenjiecloud** [comment]
上一版本的confirm事件返回默认的是new Date()，1.2.2版本confirm事件返回默认的2020年03月25日 13:14 这个需要怎么来修改呢？

**Comment by TangSY** [comment]
唉哟，把这个给漏了，我改回去，稍等。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Asaki"<notifications@github.com&gt;; 
发送时间: 2020年3月25日(星期三) 上午10:18
收件人: "TangSY/vue-hash-calendar"<vue-hash-calendar@noreply.github.com&gt;; 
抄送: "【T】"<337828932@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [TangSY/vue-hash-calendar] 选择时间有点bug (#15)





 
上一版本的confirm事件返回默认的是new Date()，1.2.2版本confirm事件返回默认的2020年03月25日 13:14 这个需要怎么来修改呢？

**Comment by TangSY** [comment]
或者你传一个&nbsp;format&nbsp;属性，自动返回你想要的时间格式。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Asaki"<notifications@github.com&gt;; 
发送时间: 2020年3月25日(星期三) 上午10:18
收件人: "TangSY/vue-hash-calendar"<vue-hash-calendar@noreply.github.com&gt;; 
抄送: "【T】"<337828932@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [TangSY/vue-hash-calendar] 选择时间有点bug (#15)





 
上一版本的confirm事件返回默认的是new Date()，1.2.2版本confirm事件返回默认的2020年03月25日 13:14 这个需要怎么来修改呢？

**Comment by TangSY** [comment]
改回去了，1.2.3&nbsp;版本&nbsp;依旧默认返回new Date()



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Asaki"<notifications@github.com&gt;; 
发送时间: 2020年3月25日(星期三) 上午10:18
收件人: "TangSY/vue-hash-calendar"<vue-hash-calendar@noreply.github.com&gt;; 
抄送: "【T】"<337828932@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [TangSY/vue-hash-calendar] 选择时间有点bug (#15)





 
上一版本的confirm事件返回默认的是new Date()，1.2.2版本confirm事件返回默认的2020年03月25日 13:14 这个需要怎么来修改呢？
