### ISSUE TITLE
可以在下面填上农历吗？

### ISSUE THREAD

**Issue by shixuwen** [TangSY/vue-hash-calendar#16]
也不一定是农历。就是在下面添加一个可以供编辑的字符串

**Comment by TangSY** [comment]
可以，稍后加




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "shixuwen"<notifications@github.com&gt;; 
发送时间: 2020年3月25日(星期三) 下午3:30
收件人: "TangSY/vue-hash-calendar"<vue-hash-calendar@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [TangSY/vue-hash-calendar] 可以在下面填上农历吗？ (#16)





 
也不一定是农历。就是在下面添加一个可以供编辑的字符串

**Comment by TangSY** [comment]
已添加 day 插槽以及自定义className。用于自定义日历展示。更新npm包至最新版本既可使用。
