### ISSUE TITLE
好像每次显示隐藏都会导致组件高度加10px

### ISSUE THREAD

**Issue by DevinAu** [TangSY/vue-hash-calendar#17]

**Comment by TangSY** [comment]
多谢反馈，收到




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Devin Au"<notifications@github.com&gt;; 
发送时间: 2020年4月15日(星期三) 上午9:57
收件人: "TangSY/vue-hash-calendar"<vue-hash-calendar@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [TangSY/vue-hash-calendar] 好像每次显示隐藏都会导致组件高度加10px (#17)

**Comment by TangSY** [comment]
已修复，使用时更新组件npm包至最新版本即可

**Comment by DevinAu** [comment]
> 已修复，使用时更新组件npm包至最新版本即可
好的 谢谢
