### ISSUE TITLE
是否支持，被标注的日期下面进行备注功能

### ISSUE THREAD

**Issue by wzl26999821** [TangSY/vue-hash-calendar#19]
是否支持，被标注的日期下面进行备注功能

**Comment by TangSY** [comment]
使用 day slot 插槽，即可实现该功能

**Comment by wzl26999821** [comment]
您好，day slot方法，如何使用？能给个小例子吗？

**Comment by TangSY** [comment]
可以，五一假期有时间后写一个

**Comment by TangSY** [comment]
已添加 demo：https://github.com/TangSY/vue-hash-calendar/blob/dev/examples/SlotDemo.vue
可点击该链接进行查看。
