### ISSUE TITLE
周切换有bug

### ISSUE THREAD

**Issue by wzl26999821** [TangSY/vue-hash-calendar#21]
周切换，顶部年月日显示有问题，正常切换到三月，但是上面显示的是2月

**Comment by TangSY** [comment]
版本是目前为止，最新的1.2.7吗？
我这边测试了一下，是没问题的。
https://hxkj.vip/demo/calendar/，你用这个地址测试看一下（这个演示地址用的代码就是这个Github仓库的示例代码），如果还有问题麻烦录个操作 gif 图以及相关机型，多谢反馈

**Comment by wzl26999821** [comment]
手机机型是iphone5，动态图我不会弄

**Comment by wzl26999821** [comment]
并且iphone滑动会触发click事件

**Comment by TangSY** [comment]
好，收到

**Comment by chenguozhi** [comment]
遇到同样的问题，iPhone手机，视图切换后，日期不一致；可以加我微信 ，我可以协助测试13651276472

**Comment by chenguozhi** [comment]
我先升级下试试

**Comment by TangSY** [comment]
> 遇到同样的问题，iPhone手机，视图切换后，日期不一致；可以加我微信 ，我可以协助测试13651276472

@chenguozhi 你的手机也是iPhone 5

**Comment by TangSY** [comment]
> 遇到同样的问题，iPhone手机，视图切换后，日期不一致；可以加我微信 ，我可以协助测试13651276472

@chenguozhi 你的手机也是iPhone 5吗？

**Comment by TangSY** [comment]
> 我先升级下试试

@chenguozhi 升级之后是否还有该问题？

**Comment by chenguozhi** [comment]
解决了，和fastclick一起用，才会导致那个问题，去掉fastclick就好了

**Comment by TangSY** [comment]
> 解决了，和fastclick一起用，才会导致那个问题，去掉fastclick就好了

@wzl26999821 你看下是不是也是该问题导致的
