### ISSUE TITLE
怎么将每个月的1号显示为1号，而不是类似【6月】

### ISSUE THREAD

**Issue by chenguozhi** [TangSY/vue-hash-calendar#23]

**Comment by TangSY** [comment]
已添加 demo：https://github.com/TangSY/vue-hash-calendar/blob/dev/examples/FirstDayDemo.vue
可点击该链接进行查看。

**Comment by TangSY** [comment]
主要使用 day slot 插槽完成的

**Comment by chenguozhi** [comment]
了解了，十分感谢------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;TangSY&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月9日(星期二) 晚上9:14
收件人:&nbsp;&quot;TangSY/vue-hash-calendar&quot;<vue-hash-calendar@noreply.github.com&gt;;
抄送:&nbsp;&quot;陈国志&quot;<352602412@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TangSY/vue-hash-calendar] 怎么将每个月的1号显示为1号，而不是类似【6月】 (#23)
