### ISSUE TITLE
请问可不可以只显示固定的月份，其他月份滑动不过去。

### ISSUE THREAD

**Issue by booboom** [TangSY/vue-hash-calendar#25]
如题

**Comment by TangSY** [comment]
可以，得加个属性控制




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "baomer"<notifications@github.com&gt;; 
发送时间: 2020年7月13日(星期一) 晚上7:39
收件人: "TangSY/vue-hash-calendar"<vue-hash-calendar@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [TangSY/vue-hash-calendar] 请问可不可以只显示固定的月份，其他月份滑动不过去。 (#25)





 
如题

**Comment by TangSY** [comment]
已添加disabledScroll属性，用于控制禁用滑动方向，可根据当前月份进行动态控制。更新组件至V1.2.12版本即可使用，详细使用方法可参考文档




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "baomer"<notifications@github.com&gt;; 
发送时间: 2020年7月13日(星期一) 晚上7:39
收件人: "TangSY/vue-hash-calendar"<vue-hash-calendar@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [TangSY/vue-hash-calendar] 请问可不可以只显示固定的月份，其他月份滑动不过去。 (#25)





 
如题

**Comment by booboom** [comment]
🐂🍺🐂🍺！
