### ISSUE TITLE
请问下，能否添加一个周视图的收折与展开按钮

### ISSUE THREAD

**Issue by CloudHe1988** [TangSY/vue-hash-calendar#27]
请问下，能否添加一个周视图的收折与展开按钮
其他功能已经很完善了，就是开起周视图后，缺个提示用户可展开的按钮，这块看了下也没插槽，不知大佬能否抽空加下

**Comment by TangSY** [comment]
有道理，稍后加




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "CloudHe1988"<notifications@github.com&gt;; 
发送时间: 2020年7月22日(星期三) 中午11:35
收件人: "TangSY/vue-hash-calendar"<vue-hash-calendar@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [TangSY/vue-hash-calendar] 请问下，能否添加一个周视图的收折与展开按钮 (#27)





 
请问下，能否添加一个周视图的收折与展开按钮
 其他功能已经很完善了，就是开起周视图后，缺个提示用户可展开的按钮，这块看了下也没插槽，不知大佬能否抽空加下

**Comment by TangSY** [comment]
突然发现，组件可以不用加，你可以使用的时候，在日历下方直接添加一个类似的按钮就可以了，可以通过修改 isShowWeekView 的值来控制周视图的收折与展开

**Comment by TangSY** [comment]
已添加 isShowArrow 属性，控制 是否显示周月切换时的指示箭头。
已添加 arrow 插槽，用于 自定义周月切换时的指示箭头。
v1.2.21 版本已更新该功能，具体使用发放可参考文档

**Comment by starlet0822** [comment]
isShowArrow 苹果手机无效？
