### ISSUE TITLE
当在goole浏览器中 F12 【手机模式】调试，时、分可上线滑动选择，非手机模式时分上下滑动不可用

### ISSUE THREAD

**Issue by JunkeWen** [TangSY/vue-hash-calendar#30]
![1599050057(1)](https://user-images.githubusercontent.com/64882624/91981650-bdc78d80-ed5b-11ea-9301-c9392fe298aa.jpg)

**Comment by TangSY** [comment]
非手机调试模式，没有 touch 事件




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JunkeWen"<notifications@github.com&gt;; 
发送时间: 2020年9月2日(星期三) 晚上8:35
收件人: "TangSY/vue-hash-calendar"<vue-hash-calendar@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [TangSY/vue-hash-calendar] 当在goole浏览器中 F12 【手机模式】调试，时、分可上线滑动选择，非手机模式时分上下滑动不可用 (#30)

**Comment by JunkeWen** [comment]
请问那应该如何解决，准备应用于PC一体机，它是自带触摸屏的

**Comment by TangSY** [comment]
带触摸屏就不会有这个问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JunkeWen"<notifications@github.com&gt;; 
发送时间: 2020年9月2日(星期三) 晚上8:46
收件人: "TangSY/vue-hash-calendar"<vue-hash-calendar@noreply.github.com&gt;; 
抄送: "【T】"<337828932@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [TangSY/vue-hash-calendar] 当在goole浏览器中 F12 【手机模式】调试，时、分可上线滑动选择，非手机模式时分上下滑动不可用 (#30)





 
请问那应该如何解决，准备应用于PC一体机，它是自带触摸屏的

**Comment by JunkeWen** [comment]
好的 ，我试下 谢谢了
