### ISSUE TITLE
初始化日历设置成左右滑动，页面刷新时会滚动一下

### ISSUE THREAD

**Issue by Deadpool957** [TangSY/vue-hash-calendar#32]

**Comment by Deadpool957** [comment]
展示的日历会滚动一下

**Comment by TangSY** [comment]
初始化日历设置成左右滑动       是指的啥？初始化时就调用显示下一个月的方法吗？

**Comment by Deadpool957** [comment]
我设置日历只能左右滑动，页面刷新的时候，日历的日期会滚动一下

**Comment by Deadpool957** [comment]
会上下滚动一下

**Comment by TangSY** [comment]
我试了一下。这个滚动是日历本身的加载动画吧，你不设置只能左右滑动，也会有这个效果的。或者你方便录个gif图，发我邮箱吗？地址：t@tsy6.com




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Letme"<notifications@github.com&gt;; 
发送时间: 2020年10月13日(星期二) 下午3:44
收件人: "TangSY/vue-hash-calendar"<vue-hash-calendar@noreply.github.com&gt;; 
抄送: "【T】"<337828932@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [TangSY/vue-hash-calendar] 初始化日历设置成左右滑动，页面刷新时会滚动一下 (#32)





 
我设置日历只能左右滑动，页面刷新的时候，日历的日期会滚动一下
