### ISSUE TITLE
如何禁用3个月后的日期

### ISSUE THREAD

**Issue by Deadpool957** [TangSY/vue-hash-calendar#33]

**Comment by TangSY** [comment]
disabledDate(date) {
    let timestamp = date.getTime();
    if (timestamp > new Date().getTime() + 90 * 24 * 60 * 60 * 1000) {
        return true
    }

    return false
}


这是禁用90天（大概3个月）的示例，如需精确计算，得你自己根据当前返回的 date 参数推算哦

**Comment by Deadpool957** [comment]
感谢
