### ISSUE TITLE
楼主，支持初始化有效日期，类似min-date max-date这种

### ISSUE THREAD

**Issue by Deadpool957** [TangSY/vue-hash-calendar#34]

**Comment by TangSY** [comment]
其实用disabledDate属性也是可以实现的。我加一下吧，方便一些



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Letme"<notifications@github.com&gt;; 
发送时间: 2020年10月19日(星期一) 下午4:24
收件人: "TangSY/vue-hash-calendar"<vue-hash-calendar@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [TangSY/vue-hash-calendar] 楼主，支持初始化有效日期，类似min-date max-date这种 (#34)

**Comment by Deadpool957** [comment]
但是设置disabledDate后日期还是能进行滑动的，我给你发个gif

**Comment by TangSY** [comment]
我懂你意思了，初始化有效日期后，就只能有效日期范围内滑动



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Letme"<notifications@github.com&gt;; 
发送时间: 2020年10月19日(星期一) 下午4:31
收件人: "TangSY/vue-hash-calendar"<vue-hash-calendar@noreply.github.com&gt;; 
抄送: "【T】"<337828932@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [TangSY/vue-hash-calendar] 楼主，支持初始化有效日期，类似min-date max-date这种 (#34)





 
但是设置disabledDate后日期还是能进行滑动的，我给你发个gif

**Comment by Deadpool957** [comment]
就是禁用掉的日期不应该划不过的去的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TangSY/vue-hash-calendar"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月19日(星期一) 下午4:28
收件人:&nbsp;"TangSY/vue-hash-calendar"<vue-hash-calendar@noreply.github.com&gt;;
抄送:&nbsp;"l半心就够"<936412083@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TangSY/vue-hash-calendar] 楼主，支持初始化有效日期，类似min-date max-date这种 (#34)





 其实用disabledDate属性也是可以实现的。我加一下吧，方便一些 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "Letme"<notifications@github.com&amp;gt;;  
 发送时间: 2020年10月19日(星期一) 下午4:24 
 收件人: "TangSY/vue-hash-calendar"<vue-hash-calendar@noreply.github.com&amp;gt;;  
 抄送: "Subscribed"<subscribed@noreply.github.com&amp;gt;;  
 主题: [TangSY/vue-hash-calendar] 楼主，支持初始化有效日期，类似min-date max-date这种 (#34)

**Comment by Deadpool957** [comment]
是这个意思，我下了源码，研究了好长时间，不知道怎么改

**Comment by TangSY** [comment]
好，我加一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Letme"<notifications@github.com&gt;; 
发送时间: 2020年10月19日(星期一) 下午4:41
收件人: "TangSY/vue-hash-calendar"<vue-hash-calendar@noreply.github.com&gt;; 
抄送: "【T】"<337828932@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [TangSY/vue-hash-calendar] 楼主，支持初始化有效日期，类似min-date max-date这种 (#34)





 
是这个意思，我下了源码，研究了好长时间，不知道怎么改

**Comment by Deadpool957** [comment]
非常感谢

**Comment by TangSY** [comment]
已添加。更新npm包至最新版本v1.2.7即可使用。具体使用方法及属性名称可查看文档




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Letme"<notifications@github.com&gt;; 
发送时间: 2020年10月19日(星期一) 下午4:43
收件人: "TangSY/vue-hash-calendar"<vue-hash-calendar@noreply.github.com&gt;; 
抄送: "【T】"<337828932@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [TangSY/vue-hash-calendar] 楼主，支持初始化有效日期，类似min-date max-date这种 (#34)





 
非常感谢

**Comment by Deadpool957** [comment]
谢谢大佬，学习了，强

**Comment by TangSY** [comment]
哈哈，没事，给个star就好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Letme"<notifications@github.com&gt;; 
发送时间: 2020年10月20日(星期二) 下午4:48
收件人: "TangSY/vue-hash-calendar"<vue-hash-calendar@noreply.github.com&gt;; 
抄送: "【T】"<337828932@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [TangSY/vue-hash-calendar] 楼主，支持初始化有效日期，类似min-date max-date这种 (#34)





 
谢谢大佬，学习了，强
