### ISSUE TITLE
为什么设置minDate与maxDate无效

### ISSUE THREAD

**Issue by Nicer-n** [TangSY/vue-hash-calendar#36]
设置minDate与maxDate,还是能够滑动到小范围之前的日期

**Comment by TangSY** [comment]
看下你是怎么设置的

**Comment by Nicer-n** [comment]
<vue-hash-calendar :visible="true" :isShowWeekView="true" :minDate="minDate" :maxDate="maxDate">
daia中设置默认值：
   minDate:new Date("2020-10-28"),
    maxDate:new Date("2020-11-29"),

**Comment by Nicer-n** [comment]
组件中绑定 :minDate="minDate" :maxDate="maxDate"

**Comment by TangSY** [comment]
然后，还是能滑动到9月份是吧

**Comment by Nicer-n** [comment]
是的

**Comment by TangSY** [comment]
组件库用的是哪个版本的

**Comment by Nicer-n** [comment]
1.2.16

**Comment by TangSY** [comment]
这两个属性是在 1.2.17 加入的，更新下

**Comment by Nicer-n** [comment]
好的 谢谢啦

**Comment by TangSY** [comment]
嗯，有问题欢迎继续反馈
