### ISSUE TITLE
周日历模式下，在每月1号的周内左滑，左滑事件触发一遍，日期却变为两周前

### ISSUE THREAD

**Issue by zhanglin9606** [TangSY/vue-hash-calendar#42]
周日历模式下，weekStart=monday，在每月1号的周内左滑，左滑事件触发一遍，日期却变为两周前

**Comment by TangSY** [comment]
好的，我这边看下这个问题

**Comment by TangSY** [comment]
你好，我这边一直无法复现该问题哦，可否提供一下操作视频或者GIF图，可发送至邮箱 t@tsy6.com。
并注明机型，浏览器等设备信息，多谢。

**Comment by TangSY** [comment]
已修复，更新到最新版本 v1.2.29 即可
