### ISSUE TITLE
怎么取消选中的时间，即双击后取消高亮

### ISSUE THREAD

**Issue by starlet0822** [TangSY/vue-hash-calendar#48]

**Comment by TangSY** [comment]
时间只支持单选，取消不了哦

**Comment by starlet0822** [comment]
> 时间只支持单选，取消不了哦

好的，谢谢大佬，如果添加取消大概怎么实现呀？

**Comment by TangSY** [comment]
不明白你要实现啥需求。
如果你是要清除选中的时间，可以在输入框后面加个 ‘x’ 按钮，点击后赋值为空即可

**Comment by starlet0822** [comment]
> 不明白你要实现啥需求。
> 如果你是要清除选中的时间，可以在输入框后面加个 ‘x’ 按钮，点击后赋值为空即可
但是 defaultDate 限制类型为 Date 怎么设置值才不高亮，因为 目前只能new Date() 赋值

**Comment by TangSY** [comment]
感觉这种使用场景不存在吧，就像你打开日历，肯定会有个默认选项的呀，但取不取值你是可以控制的。
可以举个例子吗？或者说下你要实现的效果，最好附上相应的效果图，多谢！
