### ISSUE TITLE
大佬，请问怎么取消 当前选择的日期？就是不用高亮

### ISSUE THREAD

**Issue by starlet0822** [TangSY/vue-hash-calendar#54]

**Comment by TangSY** [comment]
暂不支持该功能



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月27日(星期二) 晚上6:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [TangSY/vue-hash-calendar] 大佬，请求怎么取消 当前选择的日期？就是不用高亮 (#54)
