### ISSUE TITLE
是否考虑加个主题颜色的属性

### ISSUE THREAD

**Issue by starlet0822** [TangSY/vue-hash-calendar#60]

**Comment by TangSY** [comment]
考虑，稍后加

**Comment by starlet0822** [comment]
好的谢谢

**Comment by starlet0822** [comment]
点击 切换月周视图按钮可否 可以做一个 $emit(‘change-view’, this.isShowWeekView)
拿到当前 isShowWeekView 值可以方便处理一些场景

**Comment by TangSY** [comment]
> 点击 切换月周视图按钮可否 可以做一个 $emit(‘change-view’, this.isShowWeekView)
> 拿到当前 isShowWeekView 值可以方便处理一些场景

slidechange 试试这个方法？

**Comment by starlet0822** [comment]
点击是无法触发到这个 slidechange 事件

**Comment by TangSY** [comment]
> 点击是无法触发到这个 slidechange 事件

已添加 点击切换月周视图按钮触发 slidechange 事件，使用最新版本 >= 1.3.15

**Comment by TangSY** [comment]
主题颜色属性 themeColor 已添加，使用最新版本 >= 1.3.17
