### ISSUE TITLE
不支持Vue3吗？

### ISSUE THREAD

**Issue by calvin844** [TangSY/vue-hash-calendar#63]
package.json
![QQ截图20210705164705](https://user-images.githubusercontent.com/52489307/124444199-eface480-ddb0-11eb-8812-48fc23890868.jpg)
main.js
![QQ截图20210705164717](https://user-images.githubusercontent.com/52489307/124444274-02271e00-ddb1-11eb-8b9b-ed01bc45883b.jpg)
components.vue
![QQ截图20210705164736](https://user-images.githubusercontent.com/52489307/124444347-1408c100-ddb1-11eb-8977-34d5ea6eb2ee.jpg)
报错：
![QQ截图20210705164750](https://user-images.githubusercontent.com/52489307/124444377-1cf99280-ddb1-11eb-9e85-19520a60bd81.jpg)

**Comment by TangSY** [comment]
暂未适配

**Comment by TangSY** [comment]
vue3 版本已更新。
github 地址：https://github.com/TangSY/vue3-hash-calendar
码云 gitee 地址：https://gitee.com/HashTang/vue3-hash-calendar

npm 导入：npm i -S vue3-hash-calendar
