### ISSUE TITLE
themeColor冲突

### ISSUE THREAD

**Issue by zdzhang** [TangSY/vue-hash-calendar#69]
设置themeColor会抹去DatetimePicker.vue
`  <div class="hash-calendar"
       :class="{'calendar_inline': model === 'inline'}"
       v-show="isShowDatetimePicker"
       :style="{'height': `${model === 'inline' ? calendarContentHeight + (isShowArrowImg ? 30 : 0) : undefined}px`}"
       @click="close">`
中绑定的style，导致高度height异常

**Comment by TangSY** [comment]
好的，我这边看看

**Comment by TangSY** [comment]
![image](https://user-images.githubusercontent.com/16008985/135301303-05f1cb02-2441-4555-95cf-dd8527dbae8f.png)
