### ISSUE TITLE
挺好看的，可惜不支持vue3

### ISSUE THREAD

**Issue by mrxzm** [TangSY/vue-hash-calendar#71]

**Comment by TangSY** [comment]
马上提供支持，国庆后更新版本

**Comment by TangSY** [comment]
vue3 版本已更新。
github 地址：https://github.com/TangSY/vue3-hash-calendar
码云 gitee 地址：https://gitee.com/HashTang/vue3-hash-calendar

npm 导入：npm i -S vue3-hash-calendar
