### ISSUE TITLE
isShowWeekView

### ISSUE THREAD

**Issue by bemzhao** [TangSY/vue-hash-calendar#75]
非常感谢作者分享这个日历组件

目前业务中有个场景是要默认显示周视图的，我在文档上找到可以传入 isShowWeekView 来实现

但实际上并没有出现预期的效果

我在 codesandbox 上复现了这个问题

![image](https://user-images.githubusercontent.com/27409590/142976028-d9010c9b-b21b-45b4-9024-3562b765fdc2.png)

[https://codesandbox.io/s/gracious-dream-d7wi2?file=/src/components/HelloWorld.vue](https://codesandbox.io/s/gracious-dream-d7wi2?file=/src/components/HelloWorld.vue)

**Comment by bemzhao** [comment]
如果我传入一个字符串 “true” 就能达到预期的效果，但我知道类型检查会告诉我该传入一个 Boolean 值..

**Comment by TangSY** [comment]
time_show 初始值改为 true

**Comment by TangSY** [comment]
当 model 为 inline 时，visible 的值必须为 true
