### ISSUE TITLE
themeColor 不传会报错

### ISSUE THREAD

**Issue by iamtomas** [TangSY/vue-hash-calendar#76]
源码：
`
<vue-hash-calendar 
        :visible.sync="isShowCalendar"
      ></vue-hash-calendar>
`

报错：
![image](https://user-images.githubusercontent.com/83901620/143556899-e9f7dd00-f319-4ec9-86ad-4fe482d069b8.png)

分析：
文档提到 themeColor 非必传，但实际结果是不传会报错，插件源码估计对 themeColor 参数的默认值设置存在问题

**Comment by TangSY** [comment]
好的，感谢反馈，我修复一下

**Comment by TangSY** [comment]
已修复
