### ISSUE TITLE
周月切换的提示箭头，快速点击会导致组件被隐藏

### ISSUE THREAD

**Issue by iamtomas** [TangSY/vue-hash-calendar#77]
现象：多次点击提示箭头，日历的高度变化计算存在问题，导致visible为false进而组件被隐藏

第一次点击：
![image](https://user-images.githubusercontent.com/83901620/143829658-7744a868-cd3a-4660-8a26-1e7a0b27e426.png)

第二次点击：
![image](https://user-images.githubusercontent.com/83901620/143829794-a9405514-196e-4e1a-923a-71b813c1961c.png)

然后快速连续点击：
![image](https://user-images.githubusercontent.com/83901620/143829955-00c54515-d6f6-4309-9fd5-1c7eae87a184.png)

分析：clone了插件源码，简单看了下，在 `packages/vueHashCalendar/src/DatetimePicker.vue` 下监听的 visible 存在问题
![image](https://user-images.githubusercontent.com/83901620/143830263-20d2f626-9821-4912-974b-af5ee045c2ea.png)
大致原因猜测是calendarTitle还没渲染完成导致offsetHeight未取到

**Comment by TangSY** [comment]
好的，我修复一下

**Comment by iamtomas** [comment]
> 好的，我修复一下

好的 npm包发版吗

**Comment by TangSY** [comment]
> > 好的，我修复一下
> 
> 好的 npm包发版吗

这边未复现，你只点击了周月切换按钮吗

**Comment by TangSY** [comment]
![GIF 2021-12-2 11-24-07](https://user-images.githubusercontent.com/16008985/144352316-3f393f9d-2c89-4bb4-bf40-6e56c9a1ecc5.gif)

**Comment by iamtomas** [comment]
源码：
```
<vue-hash-calendar
  format="YY-MM-DD"
  pickerType="date"
  :mark-date="markDate"
  :isShowWeekView="showWeekView"
  :changeYearFast="false"
  :theme-color="themeColor"
  :visible.sync="isShowCalendar"
  :isShowNotCurrentMonthDay="true"
  @change="changeCalendar"
  style="box-shadow: 0px 5px 10px 0px rgba(131, 134, 163, 0.12);"
>
  <div slot="today" @click="createRecall">
    <svg class="icon" aria-hidden="true">
      <use xlink:href="#iconxiaoxitianjia"></use>
    </svg>
  </div>
  <div slot="day" slot-scope="scope">{{scope.date.day}}</div>
  <div slot="arrow" class="calendar-arrow"></div>
</vue-hash-calendar>

```

对的，只点击了周月切换按钮，你可以试下**点那个箭头**，而不是点击切换修改状态

另外，你这个动图也有个我目前遇到的问题，就是被标记的小圆点显示不全，如果可以的话，计算得出的高度再放大一些，让小圆点显示完整些

![image](https://user-images.githubusercontent.com/83901620/144352701-20ae2a9d-3adf-48a1-9485-e0f91db1278a.png)

**Comment by TangSY** [comment]
被标记的小圆点显示不全的问题已修复。
组件被隐藏的问题无法复现，可以使用类似于 codesandbox  建一个最简在线 demo 复现一下？

**Comment by iamtomas** [comment]
> 

```
<template>
  <div id="app">
    <vue-hash-calendar
      format="YY-MM-DD"
      pickerType="date"
      :mark-date="markDate"
      :isShowWeekView="showWeekView"
      :isShowArrow="true"
      :changeYearFast="false"
      :theme-color="themeColor"
      :visible.sync="isShowCalendar"
      :isShowNotCurrentMonthDay="true"
      @change="changeCalendar"
      style="box-shadow: 0px 5px 10px 0px rgba(131, 134, 163, 0.12)"
    >
      <div slot="day" slot-scope="scope">{{ scope.date.day }}</div>
      <div slot="arrow" class="calendar-arrow"></div>
    </vue-hash-calendar>
  </div>
</template>

<script>
export default {
  name: "App",
  data() {
    return {
      isShowCalendar: true,
      markDate: [{ color: "red", date: "2021/12/03" }],
      showWeekView: true,
      themeColor: {},
    };
  },
  methods: {
    changeCalendar() {},
    createRecall() {},
  },
};
</script>

<style>
#app {
  font-family: "Avenir", Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
.calendar-arrow {
  width: 32px;
  height: 3px;
  background: #DADEF0;
  border-radius: 2px;
}
</style>

```

复现出来了，只有在使用slot="arrow"后，点击几下就隐藏了

**Comment by TangSY** [comment]
已修复。[commit](https://github.com/TangSY/vue-hash-calendar/commit/6e25f93d8647af2768342bc39f65550e2711d077)

**Comment by TangSY** [comment]
更新到 1.4.6 版本
