### ISSUE TITLE
我应该通过什么来得到年或月发生了变化

### ISSUE THREAD

**Issue by a1444942531** [TangSY/vue-hash-calendar#79]
如题
因为我设置了 maxDate 和 minDate 所以 onchange 有时候并不能好好工作

**Comment by TangSY** [comment]
只需要监听切换的变化吗，试试 slidechange

**Comment by a1444942531** [comment]
> 只需要监听切换的变化吗，技能slidechange

不 我还需要他变化后的日期 好用于请求接口已获取 markDate

**Comment by a1444942531** [comment]
> 只需要监听切换的变化吗，试试 slidechange

![image](https://user-images.githubusercontent.com/19618986/145512977-08a80d18-b341-4e86-b2b1-5635b121b64d.png)
![image](https://user-images.githubusercontent.com/19618986/145512990-8da7e0ba-9c23-4e32-ad4a-bee38871c013.png)

如果我选择下个月一号 在滑动到本月 年月日不会发生变化

**Comment by TangSY** [comment]
> > 只需要监听切换的变化吗，试试 slidechange
> 
> ![image](https://user-images.githubusercontent.com/19618986/145512977-08a80d18-b341-4e86-b2b1-5635b121b64d.png) ![image](https://user-images.githubusercontent.com/19618986/145512990-8da7e0ba-9c23-4e32-ad4a-bee38871c013.png)
> 
> 如果我选择下个月一号 在滑动到本月 年月日不会发生变化

对呀，因为你这个月的1号被禁用了，所以不会有变化

**Comment by a1444942531** [comment]
> 

确实 是我理解有问题 我把它理解成当前月份了 不好意思
