### ISSUE TITLE
关于日期标记图标

### ISSUE THREAD

**Issue by Weirongbin** [TangSY/vue-hash-calendar#9]
能否设置标记的图标类型？

**Comment by TangSY** [comment]
是在日期下面把 点 换成 图标 吗？感觉图标太大布局不太好看，图标太小又看不出效果

**Comment by Weirongbin** [comment]
就是能否设置图标在日期数字外围，一个细圈把数字包围起来。。

**Comment by TangSY** [comment]
已添加 MarkType 属性，用于控制是否采用细圈标记日期，具体可以查看文档，注意更新npm包版本至最新
