### ISSUE TITLE
以周展示时，从其他页面切换过来，日历会从第一天滚动到当前周。

### ISSUE THREAD

**Issue by Hassan-bai** [TangSY/vue-hash-calendar#93]
在A页面以周样式展示日历，点击B页面，再点击A页面，日历会从第一天滚动到当前周。
【A、B页面均为tabbar页面】

**Comment by TangSY** [comment]
可以给个在线demo？或者gif动图

**Comment by Hassan-bai** [comment]
> 可以给个在线demo？或者gif动图

把日历按 周 展示。

点展开，再点收起，就可以复现，就是先展示周那一行了，然后日历才滚动上去。

**Comment by TangSY** [comment]
未复现
