### ISSUE TITLE
自定义操作栏如何显示日期啊

### ISSUE THREAD

**Issue by zhanghojie** [TangSY/vue-hash-calendar#95]
自定义操作栏如何显示日期啊，没见有这一块的处理

**Comment by TangSY** [comment]
都自定义了，肯定自己处理呀，把获取到的日期写上去就O了

**Comment by zhanghojie** [comment]
还有一个问题，当不展示日历中的非本月日期的时候，调用农历显示js会报错length

**Comment by TangSY** [comment]
> 还有一个问题，当不展示日历中的非本月日期的时候，调用农历显示js会报错length

好的，我修复一下

**Comment by TangSY** [comment]
> 还有一个问题，当不展示日历中的非本月日期的时候，调用农历显示js会报错length

好的，我修复一下

**Comment by TangSY** [comment]
> 还有一个问题，当不展示日历中的非本月日期的时候，调用农历显示js会报错length

已修复

**Comment by zhanghojie** [comment]
这个我试了还是报错啊，重新下载了版本




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月2日(星期一) 晚上8:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TangSY/vue-hash-calendar] 自定义操作栏如何显示日期啊 (Issue #95)





 
Closed #95.
