### ISSUE TITLE
指定默认时间问题

### ISSUE THREAD

**Issue by chenprincess** [TangSY/vue-hash-calendar#97]
指定默认时间属性无法正常使用，我使用defaultDatetime属性设置默认时间，但是一直报错，如下：
![image](https://user-images.githubusercontent.com/37969075/165049645-cbf285b8-6ad4-4705-93ce-3e37340d338e.png)
![image](https://user-images.githubusercontent.com/37969075/165049664-7018b0c5-11a0-4847-bb25-0db6b6b005f4.png)
![image](https://user-images.githubusercontent.com/37969075/165049748-501ba5e7-8c1b-46c7-9b2f-a4378cc62fdf.png)

**Comment by TangSY** [comment]
只接收Date类型，对于时间字符串类型你需要用 new Date() 转换一下

**Comment by TangSY** [comment]
我这边测试正常，并且目前在线案例也运行正常。你可以提供一个在线的复现demo吗
