### ISSUE TITLE
设置日历默认收缩

### ISSUE THREAD

**Issue by llyzmp** [TangSY/vue-hash-calendar#98]
![image](https://user-images.githubusercontent.com/46045597/165422858-7b86f502-87c3-4815-8f94-8bf205eb62cc.png)

**Comment by TangSY** [comment]
<img width="867" alt="image" src="https://user-images.githubusercontent.com/16008985/165424717-e4b1194e-79a6-42b3-821a-7bbaeccd0104.png">

**Comment by llyzmp** [comment]
> <img alt="image" width="867" src="https://user-images.githubusercontent.com/16008985/165424717-e4b1194e-79a6-42b3-821a-7bbaeccd0104.png">

**Comment by llyzmp** [comment]
好的，十分感谢

**Comment by llyzmp** [comment]
> <img alt="image" width="867" src="https://user-images.githubusercontent.com/16008985/165424717-e4b1194e-79a6-42b3-821a-7bbaeccd0104.png">

好的，十分感谢
